name = "RefractionCorrection"
uuid = "39d212e8-880e-4b0d-bd63-f97b48e5fcb1"
authors = ["Vasilis Alexandridis", "Maarten Pronk"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
